name: marketing_cloud_messaging
description: A marketing cloud Flutter plugin.
version: 0.0.1
homepage: https://github.com/oddbit/flutter_facebook_app_events

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.10.0
  
dependencies:
  meta: ^1.0.4
  platform: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugin.marketing_cloud_messaging
        pluginClass: MarketingCloudMessagingPlugin
      ios:
        pluginClass: MarketingCloudMessagingPlugin
